// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteV1ApiKeysByIdData, DeleteV1ApiKeysByIdErrors, DeleteV1ApiKeysByIdResponses, GetHealthData, GetV1ApiKeysData, GetV1ApiKeysErrors, GetV1ApiKeysResponses, GetV1CreditsData, GetV1CreditsErrors, GetV1CreditsResponses, GetV1ScansByIdAnalyticsData, GetV1ScansByIdAnalyticsErrors, GetV1ScansByIdAnalyticsResponses, GetV1ScansByIdData, GetV1ScansByIdErrors, GetV1ScansByIdResponses, GetV1ScansData, GetV1ScansErrors, GetV1ScansResponses, PostV1ApiKeysData, PostV1ApiKeysErrors, PostV1ApiKeysResponses, PostV1CreditsPurchaseData, PostV1CreditsPurchaseErrors, PostV1CreditsPurchaseResponses, PostV1ScansBatchData, PostV1ScansBatchResponses, PostV1ScansData, PostV1ScansResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Returns service health status with dependency checks
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List API keys
 *
 * Retrieves all API keys for the authenticated user. Plaintext keys are never returned.
 */
export const getV1ApiKeys = <ThrowOnError extends boolean = false>(options?: Options<GetV1ApiKeysData, ThrowOnError>) => (options?.client ?? client).get<GetV1ApiKeysResponses, GetV1ApiKeysErrors, ThrowOnError>({ url: '/v1/api-keys/', ...options });

/**
 * Create a new API key
 *
 * Creates a new API key for the authenticated user. The plaintext key is only returned once in this response.
 */
export const postV1ApiKeys = <ThrowOnError extends boolean = false>(options: Options<PostV1ApiKeysData, ThrowOnError>) => (options.client ?? client).post<PostV1ApiKeysResponses, PostV1ApiKeysErrors, ThrowOnError>({
    url: '/v1/api-keys/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke an API key
 *
 * Revokes an API key by setting its revokedAt timestamp. The key will no longer be valid for authentication.
 */
export const deleteV1ApiKeysById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1ApiKeysByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1ApiKeysByIdResponses, DeleteV1ApiKeysByIdErrors, ThrowOnError>({ url: '/v1/api-keys/{id}', ...options });

/**
 * List scan jobs
 *
 * Returns the user's scan jobs, most recent first. Optional query batchId to list only jobs from a batch (e.g. from POST /v1/scans/batch).
 */
export const getV1Scans = <ThrowOnError extends boolean = false>(options?: Options<GetV1ScansData, ThrowOnError>) => (options?.client ?? client).get<GetV1ScansResponses, GetV1ScansErrors, ThrowOnError>({ url: '/v1/scans/', ...options });

/**
 * Create a new URL scan job
 *
 * Creates a new URL scan job and deducts credits from the user's wallet
 */
export const postV1Scans = <ThrowOnError extends boolean = false>(options: Options<PostV1ScansData, ThrowOnError>) => (options.client ?? client).post<PostV1ScansResponses, unknown, ThrowOnError>({
    url: '/v1/scans/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a batch of URL scan jobs
 *
 * Creates multiple scan jobs in one request. Deducts credits for each URL. Max 50 URLs per batch. Returns batchId for listing via GET /v1/scans?batchId=.
 */
export const postV1ScansBatch = <ThrowOnError extends boolean = false>(options: Options<PostV1ScansBatchData, ThrowOnError>) => (options.client ?? client).post<PostV1ScansBatchResponses, unknown, ThrowOnError>({
    url: '/v1/scans/batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get scan analytics (LLM calls)
 *
 * Returns observability data for a scan job: LLM calls (triage, vision, synthesis) with tokens, cost, latency.
 */
export const getV1ScansByIdAnalytics = <ThrowOnError extends boolean = false>(options: Options<GetV1ScansByIdAnalyticsData, ThrowOnError>) => (options.client ?? client).get<GetV1ScansByIdAnalyticsResponses, GetV1ScansByIdAnalyticsErrors, ThrowOnError>({ url: '/v1/scans/{id}/analytics', ...options });

/**
 * Get scan result by job ID
 *
 * Retrieves the scan result for a specific job ID. Returns the full result if completed, or status if in progress.
 */
export const getV1ScansById = <ThrowOnError extends boolean = false>(options: Options<GetV1ScansByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1ScansByIdResponses, GetV1ScansByIdErrors, ThrowOnError>({ url: '/v1/scans/{id}', ...options });

/**
 * Get credit balance
 *
 * Retrieves the current credit balance for the user
 */
export const getV1Credits = <ThrowOnError extends boolean = false>(options?: Options<GetV1CreditsData, ThrowOnError>) => (options?.client ?? client).get<GetV1CreditsResponses, GetV1CreditsErrors, ThrowOnError>({ url: '/v1/credits/', ...options });

/**
 * Purchase credits
 *
 * Purchase credits using crypto or other payment methods. This is a stub implementation.
 */
export const postV1CreditsPurchase = <ThrowOnError extends boolean = false>(options: Options<PostV1CreditsPurchaseData, ThrowOnError>) => (options.client ?? client).post<PostV1CreditsPurchaseResponses, PostV1CreditsPurchaseErrors, ThrowOnError>({
    url: '/v1/credits/purchase',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
