// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetV1ApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/api-keys/';
};

export type GetV1ApiKeysErrors = {
    /**
     * Response for status 500
     */
    500: unknown;
};

export type GetV1ApiKeysResponses = {
    /**
     * Response for status 200
     */
    200: unknown;
};

export type PostV1ApiKeysData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/v1/api-keys/';
};

export type PostV1ApiKeysErrors = {
    /**
     * Response for status 500
     */
    500: unknown;
};

export type PostV1ApiKeysResponses = {
    /**
     * Response for status 201
     */
    201: unknown;
};

export type DeleteV1ApiKeysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/api-keys/{id}';
};

export type DeleteV1ApiKeysByIdErrors = {
    /**
     * Response for status 400
     */
    400: unknown;
    /**
     * Response for status 404
     */
    404: unknown;
    /**
     * Response for status 500
     */
    500: unknown;
};

export type DeleteV1ApiKeysByIdResponses = {
    /**
     * Response for status 200
     */
    200: unknown;
};

export type GetV1ScansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/scans/';
};

export type GetV1ScansErrors = {
    /**
     * Insufficient scope (requires scan:read)
     */
    403: unknown;
    /**
     * Server error
     */
    500: unknown;
};

export type GetV1ScansResponses = {
    /**
     * List of scan jobs
     */
    200: unknown;
};

export type PostV1ScansData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/v1/scans/';
};

export type PostV1ScansResponses = {
    /**
     * Response for status 201
     */
    201: unknown;
};

export type PostV1ScansBatchData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/v1/scans/batch';
};

export type PostV1ScansBatchResponses = {
    /**
     * Response for status 201
     */
    201: unknown;
};

export type GetV1ScansByIdAnalyticsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/scans/{id}/analytics';
};

export type GetV1ScansByIdAnalyticsErrors = {
    /**
     * Insufficient scope (requires scan:read)
     */
    403: unknown;
    /**
     * Scan job not found
     */
    404: unknown;
    /**
     * Server error
     */
    500: unknown;
};

export type GetV1ScansByIdAnalyticsResponses = {
    /**
     * Scan analytics
     */
    200: unknown;
};

export type GetV1ScansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/scans/{id}';
};

export type GetV1ScansByIdErrors = {
    /**
     * Response for status 404
     */
    404: unknown;
    /**
     * Response for status 500
     */
    500: unknown;
};

export type GetV1ScansByIdResponses = {
    /**
     * Response for status 200
     */
    200: unknown;
};

export type GetV1CreditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/credits/';
};

export type GetV1CreditsErrors = {
    /**
     * Response for status 500
     */
    500: unknown;
};

export type GetV1CreditsResponses = {
    /**
     * Response for status 200
     */
    200: unknown;
};

export type PostV1CreditsPurchaseData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/v1/credits/purchase';
};

export type PostV1CreditsPurchaseErrors = {
    /**
     * Response for status 400
     */
    400: unknown;
    /**
     * Response for status 402
     */
    402: unknown;
    /**
     * Response for status 500
     */
    500: unknown;
};

export type PostV1CreditsPurchaseResponses = {
    /**
     * Response for status 201
     */
    201: unknown;
};
