// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiKeyCreation = {
    /**
     * Human-readable name for the API key
     */
    name: string;
    /**
     * Optional expiration date (ISO 8601)
     */
    expiresAt?: string;
    /**
     * API key scopes/permissions
     */
    scopes: Array<'scan:read' | 'scan:write' | 'credits:read' | 'credits:write'>;
};

export type CreateApiKeyResponse = {
    id: string;
    /**
     * Plaintext API key (only shown once)
     */
    key: string;
    name: string;
    createdAt: string;
};

export type ApiKeyListResponse = Array<{
    id: string;
    name: string;
    scopes: Array<string>;
    expiresAt: string | null;
    lastUsedAt: string | null;
    createdAt: string;
    revokedAt: string | null;
}>;

export type RevokeApiKeyResponse = {
    /**
     * ID of the revoked API key
     */
    id: string;
};

export type ErrorResponse = {
    error: {
        /**
         * Machine-readable error code
         */
        code: string;
        /**
         * Human-readable error message
         */
        message: string;
        /**
         * Additional error details
         */
        details?: {
            [key: string]: unknown;
        };
    };
    timestamp: string;
    requestId?: string;
};

export type CreateScanRequest = {
    url: string;
    /**
     * Optional metadata to associate with the scan
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type CreateScanResponse = {
    /**
     * Scan job ID
     */
    id: string;
    /**
     * Current state of the scan job. COMPLETED when returned from cache (deduplicated); in-progress states when a new or in-flight job is returned.
     */
    state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED';
    /**
     * True if this request returned an existing scan (in-flight or cached completed) instead of creating a new one
     */
    deduplicated?: boolean;
};

export type CreateBatchScanRequest = {
    urls: Array<string>;
};

export type CreateBatchScanResponse = {
    /**
     * Batch ID for listing jobs by batch
     */
    batchId: string;
    jobs: Array<{
        /**
         * Scan job ID
         */
        id: string;
        /**
         * Current state (may be in-progress if deduplicated)
         */
        state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED' | 'FAILED' | 'TIMED_OUT';
        /**
         * Scanned URL
         */
        url: string;
        /**
         * True if this URL returned an existing in-flight scan instead of creating a new one
         */
        deduplicated?: boolean;
    }>;
};

export type ScanResponse = {
    id: string;
    url: string;
    state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED' | 'FAILED' | 'TIMED_OUT';
    createdAt: string;
    updatedAt: string;
    errorMessage?: string | null;
    startedAt?: string | null;
    completedAt?: string | null;
    timeoutAt?: string | null;
    durationMs?: number | null;
    workerId?: string | null;
    result: {
        riskScore: number;
        categories: Array<string>;
        confidenceScore: number;
        reasoning: string;
        indicators: Array<string>;
        contentHash: string;
        httpStatus: number | null;
        httpHeaders: {
            [key: string]: string;
        };
        contentType: string | null;
        modelUsed: string;
        analysisMetadata?: {
            [key: string]: unknown;
        };
    } | null;
};

export type PurchaseCreditsRequest = {
    amount: number;
};

export type PurchaseCreditsResponse = {
    id: string;
    userId: string;
    amount: number;
    status: string;
    createdAt: string;
    completedAt: string;
    newBalance: number;
};

export type CreditBalanceResponse = {
    /**
     * Current credit balance
     */
    balance: number;
    /**
     * User ID
     */
    userId: string;
    updatedAt: string;
};

export type UserSettings = {
    /**
     * Clerk user ID (format: user_xxxxx)
     */
    clerkUserId: string;
    createdAt: string;
    updatedAt: string;
    metadata?: {
        [key: string]: unknown;
    };
    safeDomainPatterns: Array<string>;
    unsafeDomainPatterns: Array<string>;
};

export type UpdateUserSettings = {
    safeDomainPatterns?: Array<string>;
    unsafeDomainPatterns?: Array<string>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetV1ApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/api-keys/';
};

export type GetV1ApiKeysErrors = {
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type GetV1ApiKeysError = GetV1ApiKeysErrors[keyof GetV1ApiKeysErrors];

export type GetV1ApiKeysResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        scopes: Array<string>;
        expiresAt: string | null;
        lastUsedAt: string | null;
        createdAt: string;
        revokedAt: string | null;
    }>;
};

export type GetV1ApiKeysResponse = GetV1ApiKeysResponses[keyof GetV1ApiKeysResponses];

export type PostV1ApiKeysData = {
    body: {
        /**
         * Human-readable name for the API key
         */
        name: string;
        /**
         * Optional expiration date (ISO 8601)
         */
        expiresAt?: string;
        /**
         * API key scopes/permissions
         */
        scopes: Array<'scan:read' | 'scan:write' | 'credits:read' | 'credits:write'>;
    };
    path?: never;
    query?: never;
    url: '/v1/api-keys/';
};

export type PostV1ApiKeysErrors = {
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type PostV1ApiKeysError = PostV1ApiKeysErrors[keyof PostV1ApiKeysErrors];

export type PostV1ApiKeysResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        /**
         * Plaintext API key (only shown once)
         */
        key: string;
        name: string;
        createdAt: string;
    };
};

export type PostV1ApiKeysResponse = PostV1ApiKeysResponses[keyof PostV1ApiKeysResponses];

export type DeleteV1ApiKeysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/api-keys/{id}';
};

export type DeleteV1ApiKeysByIdErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 404
     */
    404: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type DeleteV1ApiKeysByIdError = DeleteV1ApiKeysByIdErrors[keyof DeleteV1ApiKeysByIdErrors];

export type DeleteV1ApiKeysByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        /**
         * ID of the revoked API key
         */
        id: string;
    };
};

export type DeleteV1ApiKeysByIdResponse = DeleteV1ApiKeysByIdResponses[keyof DeleteV1ApiKeysByIdResponses];

export type GetV1ScansData = {
    body?: never;
    path?: never;
    query?: {
        batchId?: string;
    };
    url: '/v1/scans/';
};

export type GetV1ScansErrors = {
    /**
     * Insufficient scope (requires scan:read)
     */
    403: unknown;
    /**
     * Server error
     */
    500: unknown;
};

export type GetV1ScansResponses = {
    /**
     * List of scan jobs
     */
    200: unknown;
};

export type PostV1ScansData = {
    body: {
        url: string;
        /**
         * Optional metadata to associate with the scan
         */
        metadata?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/v1/scans/';
};

export type PostV1ScansResponses = {
    /**
     * Response for status 201
     */
    201: {
        /**
         * Scan job ID
         */
        id: string;
        /**
         * Current state of the scan job. COMPLETED when returned from cache (deduplicated); in-progress states when a new or in-flight job is returned.
         */
        state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED';
        /**
         * True if this request returned an existing scan (in-flight or cached completed) instead of creating a new one
         */
        deduplicated?: boolean;
    };
};

export type PostV1ScansResponse = PostV1ScansResponses[keyof PostV1ScansResponses];

export type PostV1ScansBatchData = {
    body: {
        urls: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v1/scans/batch';
};

export type PostV1ScansBatchResponses = {
    /**
     * Response for status 201
     */
    201: {
        /**
         * Batch ID for listing jobs by batch
         */
        batchId: string;
        jobs: Array<{
            /**
             * Scan job ID
             */
            id: string;
            /**
             * Current state (may be in-progress if deduplicated)
             */
            state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED' | 'FAILED' | 'TIMED_OUT';
            /**
             * Scanned URL
             */
            url: string;
            /**
             * True if this URL returned an existing in-flight scan instead of creating a new one
             */
            deduplicated?: boolean;
        }>;
    };
};

export type PostV1ScansBatchResponse = PostV1ScansBatchResponses[keyof PostV1ScansBatchResponses];

export type GetV1ScansByIdAnalyticsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/scans/{id}/analytics';
};

export type GetV1ScansByIdAnalyticsErrors = {
    /**
     * Insufficient scope (requires scan:read)
     */
    403: unknown;
    /**
     * Scan job not found
     */
    404: unknown;
    /**
     * Server error
     */
    500: unknown;
};

export type GetV1ScansByIdAnalyticsResponses = {
    /**
     * Scan analytics
     */
    200: unknown;
};

export type GetV1ScansByIdEventsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/scans/{id}/events';
};

export type GetV1ScansByIdEventsErrors = {
    /**
     * Insufficient scope (requires scan:read)
     */
    403: unknown;
    /**
     * Scan job not found
     */
    404: unknown;
};

export type GetV1ScansByIdEventsResponses = {
    /**
     * SSE stream
     */
    200: unknown;
};

export type GetV1ScansByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/scans/{id}';
};

export type GetV1ScansByIdErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type GetV1ScansByIdError = GetV1ScansByIdErrors[keyof GetV1ScansByIdErrors];

export type GetV1ScansByIdResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        url: string;
        state: 'QUEUED' | 'FETCHING' | 'ANALYZING' | 'COMPLETED' | 'FAILED' | 'TIMED_OUT';
        createdAt: string;
        updatedAt: string;
        errorMessage?: string | null;
        startedAt?: string | null;
        completedAt?: string | null;
        timeoutAt?: string | null;
        durationMs?: number | null;
        workerId?: string | null;
        result: {
            riskScore: number;
            categories: Array<string>;
            confidenceScore: number;
            reasoning: string;
            indicators: Array<string>;
            contentHash: string;
            httpStatus: number | null;
            httpHeaders: {
                [key: string]: string;
            };
            contentType: string | null;
            modelUsed: string;
            analysisMetadata?: {
                [key: string]: unknown;
            };
        } | null;
    };
};

export type GetV1ScansByIdResponse = GetV1ScansByIdResponses[keyof GetV1ScansByIdResponses];

export type GetV1CreditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/credits/';
};

export type GetV1CreditsErrors = {
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type GetV1CreditsError = GetV1CreditsErrors[keyof GetV1CreditsErrors];

export type GetV1CreditsResponses = {
    /**
     * Response for status 200
     */
    200: {
        /**
         * Current credit balance
         */
        balance: number;
        /**
         * User ID
         */
        userId: string;
        updatedAt: string;
    };
};

export type GetV1CreditsResponse = GetV1CreditsResponses[keyof GetV1CreditsResponses];

export type PostV1CreditsPurchaseData = {
    body: {
        amount: number;
    };
    path?: never;
    query?: never;
    url: '/v1/credits/purchase';
};

export type PostV1CreditsPurchaseErrors = {
    /**
     * Response for status 400
     */
    400: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 402
     */
    402: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type PostV1CreditsPurchaseError = PostV1CreditsPurchaseErrors[keyof PostV1CreditsPurchaseErrors];

export type PostV1CreditsPurchaseResponses = {
    /**
     * Response for status 201
     */
    201: {
        id: string;
        userId: string;
        amount: number;
        status: string;
        createdAt: string;
        completedAt: string;
        newBalance: number;
    };
};

export type PostV1CreditsPurchaseResponse = PostV1CreditsPurchaseResponses[keyof PostV1CreditsPurchaseResponses];

export type GetV1SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/settings/';
};

export type GetV1SettingsErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type GetV1SettingsError = GetV1SettingsErrors[keyof GetV1SettingsErrors];

export type GetV1SettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        /**
         * Clerk user ID (format: user_xxxxx)
         */
        clerkUserId: string;
        createdAt: string;
        updatedAt: string;
        metadata?: {
            [key: string]: unknown;
        };
        safeDomainPatterns: Array<string>;
        unsafeDomainPatterns: Array<string>;
    };
};

export type GetV1SettingsResponse = GetV1SettingsResponses[keyof GetV1SettingsResponses];

export type PutV1SettingsData = {
    body: {
        safeDomainPatterns?: Array<string>;
        unsafeDomainPatterns?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v1/settings/';
};

export type PutV1SettingsErrors = {
    /**
     * Response for status 404
     */
    404: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
    /**
     * Response for status 500
     */
    500: {
        error: {
            /**
             * Machine-readable error code
             */
            code: string;
            /**
             * Human-readable error message
             */
            message: string;
            /**
             * Additional error details
             */
            details?: {
                [key: string]: unknown;
            };
        };
        timestamp: string;
        requestId?: string;
    };
};

export type PutV1SettingsError = PutV1SettingsErrors[keyof PutV1SettingsErrors];

export type PutV1SettingsResponses = {
    /**
     * Response for status 200
     */
    200: {
        /**
         * Clerk user ID (format: user_xxxxx)
         */
        clerkUserId: string;
        createdAt: string;
        updatedAt: string;
        metadata?: {
            [key: string]: unknown;
        };
        safeDomainPatterns: Array<string>;
        unsafeDomainPatterns: Array<string>;
    };
};

export type PutV1SettingsResponse = PutV1SettingsResponses[keyof PutV1SettingsResponses];
