// Package safeurl provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package safeurl

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PostV1ApiKeysJSONBodyScopes.
const (
	PostV1ApiKeysJSONBodyScopesCreditsRead  PostV1ApiKeysJSONBodyScopes = "credits:read"
	PostV1ApiKeysJSONBodyScopesCreditsWrite PostV1ApiKeysJSONBodyScopes = "credits:write"
	PostV1ApiKeysJSONBodyScopesScanRead     PostV1ApiKeysJSONBodyScopes = "scan:read"
	PostV1ApiKeysJSONBodyScopesScanWrite    PostV1ApiKeysJSONBodyScopes = "scan:write"
)

// Valid indicates whether the value is a known member of the PostV1ApiKeysJSONBodyScopes enum.
func (e PostV1ApiKeysJSONBodyScopes) Valid() bool {
	switch e {
	case PostV1ApiKeysJSONBodyScopesCreditsRead:
		return true
	case PostV1ApiKeysJSONBodyScopesCreditsWrite:
		return true
	case PostV1ApiKeysJSONBodyScopesScanRead:
		return true
	case PostV1ApiKeysJSONBodyScopesScanWrite:
		return true
	default:
		return false
	}
}

// Defines values for PostV1ApiKeysFormdataBodyScopes.
const (
	PostV1ApiKeysFormdataBodyScopesCreditsRead  PostV1ApiKeysFormdataBodyScopes = "credits:read"
	PostV1ApiKeysFormdataBodyScopesCreditsWrite PostV1ApiKeysFormdataBodyScopes = "credits:write"
	PostV1ApiKeysFormdataBodyScopesScanRead     PostV1ApiKeysFormdataBodyScopes = "scan:read"
	PostV1ApiKeysFormdataBodyScopesScanWrite    PostV1ApiKeysFormdataBodyScopes = "scan:write"
)

// Valid indicates whether the value is a known member of the PostV1ApiKeysFormdataBodyScopes enum.
func (e PostV1ApiKeysFormdataBodyScopes) Valid() bool {
	switch e {
	case PostV1ApiKeysFormdataBodyScopesCreditsRead:
		return true
	case PostV1ApiKeysFormdataBodyScopesCreditsWrite:
		return true
	case PostV1ApiKeysFormdataBodyScopesScanRead:
		return true
	case PostV1ApiKeysFormdataBodyScopesScanWrite:
		return true
	default:
		return false
	}
}

// Defines values for PostV1ApiKeysMultipartBodyScopes.
const (
	CreditsRead  PostV1ApiKeysMultipartBodyScopes = "credits:read"
	CreditsWrite PostV1ApiKeysMultipartBodyScopes = "credits:write"
	ScanRead     PostV1ApiKeysMultipartBodyScopes = "scan:read"
	ScanWrite    PostV1ApiKeysMultipartBodyScopes = "scan:write"
)

// Valid indicates whether the value is a known member of the PostV1ApiKeysMultipartBodyScopes enum.
func (e PostV1ApiKeysMultipartBodyScopes) Valid() bool {
	switch e {
	case CreditsRead:
		return true
	case CreditsWrite:
		return true
	case ScanRead:
		return true
	case ScanWrite:
		return true
	default:
		return false
	}
}

// PostV1ApiKeysJSONBody defines parameters for PostV1ApiKeys.
type PostV1ApiKeysJSONBody struct {
	// ExpiresAt Optional expiration date (ISO 8601)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Name Human-readable name for the API key
	Name string `json:"name"`

	// Scopes API key scopes/permissions
	Scopes []PostV1ApiKeysJSONBodyScopes `json:"scopes"`
}

// PostV1ApiKeysFormdataBody defines parameters for PostV1ApiKeys.
type PostV1ApiKeysFormdataBody struct {
	// ExpiresAt Optional expiration date (ISO 8601)
	ExpiresAt *time.Time `form:"expiresAt,omitempty" json:"expiresAt,omitempty"`

	// Name Human-readable name for the API key
	Name string `form:"name" json:"name"`

	// Scopes API key scopes/permissions
	Scopes []PostV1ApiKeysFormdataBodyScopes `form:"scopes" json:"scopes"`
}

// PostV1ApiKeysMultipartBody defines parameters for PostV1ApiKeys.
type PostV1ApiKeysMultipartBody struct {
	// ExpiresAt Optional expiration date (ISO 8601)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Name Human-readable name for the API key
	Name string `json:"name"`

	// Scopes API key scopes/permissions
	Scopes []PostV1ApiKeysMultipartBodyScopes `json:"scopes"`
}

// PostV1ApiKeysJSONBodyScopes defines parameters for PostV1ApiKeys.
type PostV1ApiKeysJSONBodyScopes string

// PostV1ApiKeysFormdataBodyScopes defines parameters for PostV1ApiKeys.
type PostV1ApiKeysFormdataBodyScopes string

// PostV1ApiKeysMultipartBodyScopes defines parameters for PostV1ApiKeys.
type PostV1ApiKeysMultipartBodyScopes string

// PostV1CreditsPurchaseJSONBody defines parameters for PostV1CreditsPurchase.
type PostV1CreditsPurchaseJSONBody struct {
	Amount int `json:"amount"`
}

// PostV1CreditsPurchaseFormdataBody defines parameters for PostV1CreditsPurchase.
type PostV1CreditsPurchaseFormdataBody struct {
	Amount int `form:"amount" json:"amount"`
}

// PostV1CreditsPurchaseMultipartBody defines parameters for PostV1CreditsPurchase.
type PostV1CreditsPurchaseMultipartBody struct {
	Amount int `json:"amount"`
}

// GetV1ScansParams defines parameters for GetV1Scans.
type GetV1ScansParams struct {
	BatchId *openapi_types.UUID `form:"batchId,omitempty" json:"batchId,omitempty"`
}

// PostV1ScansJSONBody defines parameters for PostV1Scans.
type PostV1ScansJSONBody struct {
	// Metadata Optional metadata to associate with the scan
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Url      string                  `json:"url"`
}

// PostV1ScansFormdataBody defines parameters for PostV1Scans.
type PostV1ScansFormdataBody struct {
	// Metadata Optional metadata to associate with the scan
	Metadata *map[string]interface{} `form:"metadata,omitempty" json:"metadata,omitempty"`
	Url      string                  `form:"url" json:"url"`
}

// PostV1ScansMultipartBody defines parameters for PostV1Scans.
type PostV1ScansMultipartBody struct {
	// Metadata Optional metadata to associate with the scan
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Url      string                  `json:"url"`
}

// PostV1ScansBatchJSONBody defines parameters for PostV1ScansBatch.
type PostV1ScansBatchJSONBody struct {
	Urls []string `json:"urls"`
}

// PostV1ScansBatchFormdataBody defines parameters for PostV1ScansBatch.
type PostV1ScansBatchFormdataBody struct {
	Urls []string `form:"urls" json:"urls"`
}

// PostV1ScansBatchMultipartBody defines parameters for PostV1ScansBatch.
type PostV1ScansBatchMultipartBody struct {
	Urls []string `json:"urls"`
}

// PutV1SettingsJSONBody defines parameters for PutV1Settings.
type PutV1SettingsJSONBody struct {
	SafeDomainPatterns   *[]string `json:"safeDomainPatterns,omitempty"`
	UnsafeDomainPatterns *[]string `json:"unsafeDomainPatterns,omitempty"`
}

// PutV1SettingsFormdataBody defines parameters for PutV1Settings.
type PutV1SettingsFormdataBody struct {
	SafeDomainPatterns   *[]string `form:"safeDomainPatterns,omitempty" json:"safeDomainPatterns,omitempty"`
	UnsafeDomainPatterns *[]string `form:"unsafeDomainPatterns,omitempty" json:"unsafeDomainPatterns,omitempty"`
}

// PutV1SettingsMultipartBody defines parameters for PutV1Settings.
type PutV1SettingsMultipartBody struct {
	SafeDomainPatterns   *[]string `json:"safeDomainPatterns,omitempty"`
	UnsafeDomainPatterns *[]string `json:"unsafeDomainPatterns,omitempty"`
}

// PostV1ApiKeysJSONRequestBody defines body for PostV1ApiKeys for application/json ContentType.
type PostV1ApiKeysJSONRequestBody PostV1ApiKeysJSONBody

// PostV1ApiKeysFormdataRequestBody defines body for PostV1ApiKeys for application/x-www-form-urlencoded ContentType.
type PostV1ApiKeysFormdataRequestBody PostV1ApiKeysFormdataBody

// PostV1ApiKeysMultipartRequestBody defines body for PostV1ApiKeys for multipart/form-data ContentType.
type PostV1ApiKeysMultipartRequestBody PostV1ApiKeysMultipartBody

// PostV1CreditsPurchaseJSONRequestBody defines body for PostV1CreditsPurchase for application/json ContentType.
type PostV1CreditsPurchaseJSONRequestBody PostV1CreditsPurchaseJSONBody

// PostV1CreditsPurchaseFormdataRequestBody defines body for PostV1CreditsPurchase for application/x-www-form-urlencoded ContentType.
type PostV1CreditsPurchaseFormdataRequestBody PostV1CreditsPurchaseFormdataBody

// PostV1CreditsPurchaseMultipartRequestBody defines body for PostV1CreditsPurchase for multipart/form-data ContentType.
type PostV1CreditsPurchaseMultipartRequestBody PostV1CreditsPurchaseMultipartBody

// PostV1ScansJSONRequestBody defines body for PostV1Scans for application/json ContentType.
type PostV1ScansJSONRequestBody PostV1ScansJSONBody

// PostV1ScansFormdataRequestBody defines body for PostV1Scans for application/x-www-form-urlencoded ContentType.
type PostV1ScansFormdataRequestBody PostV1ScansFormdataBody

// PostV1ScansMultipartRequestBody defines body for PostV1Scans for multipart/form-data ContentType.
type PostV1ScansMultipartRequestBody PostV1ScansMultipartBody

// PostV1ScansBatchJSONRequestBody defines body for PostV1ScansBatch for application/json ContentType.
type PostV1ScansBatchJSONRequestBody PostV1ScansBatchJSONBody

// PostV1ScansBatchFormdataRequestBody defines body for PostV1ScansBatch for application/x-www-form-urlencoded ContentType.
type PostV1ScansBatchFormdataRequestBody PostV1ScansBatchFormdataBody

// PostV1ScansBatchMultipartRequestBody defines body for PostV1ScansBatch for multipart/form-data ContentType.
type PostV1ScansBatchMultipartRequestBody PostV1ScansBatchMultipartBody

// PutV1SettingsJSONRequestBody defines body for PutV1Settings for application/json ContentType.
type PutV1SettingsJSONRequestBody PutV1SettingsJSONBody

// PutV1SettingsFormdataRequestBody defines body for PutV1Settings for application/x-www-form-urlencoded ContentType.
type PutV1SettingsFormdataRequestBody PutV1SettingsFormdataBody

// PutV1SettingsMultipartRequestBody defines body for PutV1Settings for multipart/form-data ContentType.
type PutV1SettingsMultipartRequestBody PutV1SettingsMultipartBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ApiKeys request
	GetV1ApiKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1ApiKeysWithBody request with any body
	PostV1ApiKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ApiKeys(ctx context.Context, body PostV1ApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ApiKeysWithFormdataBody(ctx context.Context, body PostV1ApiKeysFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1ApiKeysById request
	DeleteV1ApiKeysById(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Credits request
	GetV1Credits(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1CreditsPurchaseWithBody request with any body
	PostV1CreditsPurchaseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1CreditsPurchase(ctx context.Context, body PostV1CreditsPurchaseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1CreditsPurchaseWithFormdataBody(ctx context.Context, body PostV1CreditsPurchaseFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Scans request
	GetV1Scans(ctx context.Context, params *GetV1ScansParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1ScansWithBody request with any body
	PostV1ScansWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1Scans(ctx context.Context, body PostV1ScansJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ScansWithFormdataBody(ctx context.Context, body PostV1ScansFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1ScansBatchWithBody request with any body
	PostV1ScansBatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ScansBatch(ctx context.Context, body PostV1ScansBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1ScansBatchWithFormdataBody(ctx context.Context, body PostV1ScansBatchFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ScansById request
	GetV1ScansById(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ScansByIdAnalytics request
	GetV1ScansByIdAnalytics(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ScansByIdEvents request
	GetV1ScansByIdEvents(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Settings request
	GetV1Settings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutV1SettingsWithBody request with any body
	PutV1SettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutV1Settings(ctx context.Context, body PutV1SettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutV1SettingsWithFormdataBody(ctx context.Context, body PutV1SettingsFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ApiKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ApiKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ApiKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ApiKeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ApiKeys(ctx context.Context, body PostV1ApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ApiKeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ApiKeysWithFormdataBody(ctx context.Context, body PostV1ApiKeysFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ApiKeysRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1ApiKeysById(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1ApiKeysByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Credits(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CreditsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CreditsPurchaseWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CreditsPurchaseRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CreditsPurchase(ctx context.Context, body PostV1CreditsPurchaseJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CreditsPurchaseRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1CreditsPurchaseWithFormdataBody(ctx context.Context, body PostV1CreditsPurchaseFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1CreditsPurchaseRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Scans(ctx context.Context, params *GetV1ScansParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ScansRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ScansWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1Scans(ctx context.Context, body PostV1ScansJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ScansWithFormdataBody(ctx context.Context, body PostV1ScansFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ScansBatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansBatchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ScansBatch(ctx context.Context, body PostV1ScansBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansBatchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1ScansBatchWithFormdataBody(ctx context.Context, body PostV1ScansBatchFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1ScansBatchRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ScansById(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ScansByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ScansByIdAnalytics(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ScansByIdAnalyticsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ScansByIdEvents(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ScansByIdEventsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Settings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1SettingsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutV1SettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutV1SettingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutV1Settings(ctx context.Context, body PutV1SettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutV1SettingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutV1SettingsWithFormdataBody(ctx context.Context, body PutV1SettingsFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutV1SettingsRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ApiKeysRequest generates requests for GetV1ApiKeys
func NewGetV1ApiKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/api-keys/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1ApiKeysRequest calls the generic PostV1ApiKeys builder with application/json body
func NewPostV1ApiKeysRequest(server string, body PostV1ApiKeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1ApiKeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1ApiKeysRequestWithFormdataBody calls the generic PostV1ApiKeys builder with application/x-www-form-urlencoded body
func NewPostV1ApiKeysRequestWithFormdataBody(server string, body PostV1ApiKeysFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostV1ApiKeysRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostV1ApiKeysRequestWithBody generates requests for PostV1ApiKeys with any type of body
func NewPostV1ApiKeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/api-keys/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteV1ApiKeysByIdRequest generates requests for DeleteV1ApiKeysById
func NewDeleteV1ApiKeysByIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/api-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1CreditsRequest generates requests for GetV1Credits
func NewGetV1CreditsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/credits/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1CreditsPurchaseRequest calls the generic PostV1CreditsPurchase builder with application/json body
func NewPostV1CreditsPurchaseRequest(server string, body PostV1CreditsPurchaseJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1CreditsPurchaseRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1CreditsPurchaseRequestWithFormdataBody calls the generic PostV1CreditsPurchase builder with application/x-www-form-urlencoded body
func NewPostV1CreditsPurchaseRequestWithFormdataBody(server string, body PostV1CreditsPurchaseFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostV1CreditsPurchaseRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostV1CreditsPurchaseRequestWithBody generates requests for PostV1CreditsPurchase with any type of body
func NewPostV1CreditsPurchaseRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/credits/purchase")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1ScansRequest generates requests for GetV1Scans
func NewGetV1ScansRequest(server string, params *GetV1ScansParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.BatchId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "batchId", *params.BatchId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1ScansRequest calls the generic PostV1Scans builder with application/json body
func NewPostV1ScansRequest(server string, body PostV1ScansJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1ScansRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1ScansRequestWithFormdataBody calls the generic PostV1Scans builder with application/x-www-form-urlencoded body
func NewPostV1ScansRequestWithFormdataBody(server string, body PostV1ScansFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostV1ScansRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostV1ScansRequestWithBody generates requests for PostV1Scans with any type of body
func NewPostV1ScansRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostV1ScansBatchRequest calls the generic PostV1ScansBatch builder with application/json body
func NewPostV1ScansBatchRequest(server string, body PostV1ScansBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1ScansBatchRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1ScansBatchRequestWithFormdataBody calls the generic PostV1ScansBatch builder with application/x-www-form-urlencoded body
func NewPostV1ScansBatchRequestWithFormdataBody(server string, body PostV1ScansBatchFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostV1ScansBatchRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostV1ScansBatchRequestWithBody generates requests for PostV1ScansBatch with any type of body
func NewPostV1ScansBatchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1ScansByIdRequest generates requests for GetV1ScansById
func NewGetV1ScansByIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ScansByIdAnalyticsRequest generates requests for GetV1ScansByIdAnalytics
func NewGetV1ScansByIdAnalyticsRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/%s/analytics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ScansByIdEventsRequest generates requests for GetV1ScansByIdEvents
func NewGetV1ScansByIdEventsRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/scans/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1SettingsRequest generates requests for GetV1Settings
func NewGetV1SettingsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/settings/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutV1SettingsRequest calls the generic PutV1Settings builder with application/json body
func NewPutV1SettingsRequest(server string, body PutV1SettingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutV1SettingsRequestWithBody(server, "application/json", bodyReader)
}

// NewPutV1SettingsRequestWithFormdataBody calls the generic PutV1Settings builder with application/x-www-form-urlencoded body
func NewPutV1SettingsRequestWithFormdataBody(server string, body PutV1SettingsFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPutV1SettingsRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPutV1SettingsRequestWithBody generates requests for PutV1Settings with any type of body
func NewPutV1SettingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/settings/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResp, error)

	// GetV1ApiKeysWithResponse request
	GetV1ApiKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ApiKeysResp, error)

	// PostV1ApiKeysWithBodyWithResponse request with any body
	PostV1ApiKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error)

	PostV1ApiKeysWithResponse(ctx context.Context, body PostV1ApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error)

	PostV1ApiKeysWithFormdataBodyWithResponse(ctx context.Context, body PostV1ApiKeysFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error)

	// DeleteV1ApiKeysByIdWithResponse request
	DeleteV1ApiKeysByIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteV1ApiKeysByIdResp, error)

	// GetV1CreditsWithResponse request
	GetV1CreditsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1CreditsResp, error)

	// PostV1CreditsPurchaseWithBodyWithResponse request with any body
	PostV1CreditsPurchaseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error)

	PostV1CreditsPurchaseWithResponse(ctx context.Context, body PostV1CreditsPurchaseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error)

	PostV1CreditsPurchaseWithFormdataBodyWithResponse(ctx context.Context, body PostV1CreditsPurchaseFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error)

	// GetV1ScansWithResponse request
	GetV1ScansWithResponse(ctx context.Context, params *GetV1ScansParams, reqEditors ...RequestEditorFn) (*GetV1ScansResp, error)

	// PostV1ScansWithBodyWithResponse request with any body
	PostV1ScansWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error)

	PostV1ScansWithResponse(ctx context.Context, body PostV1ScansJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error)

	PostV1ScansWithFormdataBodyWithResponse(ctx context.Context, body PostV1ScansFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error)

	// PostV1ScansBatchWithBodyWithResponse request with any body
	PostV1ScansBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error)

	PostV1ScansBatchWithResponse(ctx context.Context, body PostV1ScansBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error)

	PostV1ScansBatchWithFormdataBodyWithResponse(ctx context.Context, body PostV1ScansBatchFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error)

	// GetV1ScansByIdWithResponse request
	GetV1ScansByIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdResp, error)

	// GetV1ScansByIdAnalyticsWithResponse request
	GetV1ScansByIdAnalyticsWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdAnalyticsResp, error)

	// GetV1ScansByIdEventsWithResponse request
	GetV1ScansByIdEventsWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdEventsResp, error)

	// GetV1SettingsWithResponse request
	GetV1SettingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1SettingsResp, error)

	// PutV1SettingsWithBodyWithResponse request with any body
	PutV1SettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error)

	PutV1SettingsWithResponse(ctx context.Context, body PutV1SettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error)

	PutV1SettingsWithFormdataBodyWithResponse(ctx context.Context, body PutV1SettingsFormdataRequestBody, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error)
}

type GetHealthResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ApiKeysResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		CreatedAt  time.Time          `json:"createdAt"`
		ExpiresAt  *time.Time         `json:"expiresAt"`
		Id         openapi_types.UUID `json:"id"`
		LastUsedAt *time.Time         `json:"lastUsedAt"`
		Name       string             `json:"name"`
		RevokedAt  *time.Time         `json:"revokedAt"`
		Scopes     []string           `json:"scopes"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV1ApiKeysResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ApiKeysResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1ApiKeysResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		CreatedAt time.Time          `json:"createdAt"`
		Id        openapi_types.UUID `json:"id"`

		// Key Plaintext API key (only shown once)
		Key  string `json:"key"`
		Name string `json:"name"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r PostV1ApiKeysResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1ApiKeysResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1ApiKeysByIdResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Id ID of the revoked API key
		Id openapi_types.UUID `json:"id"`
	}
	JSON400 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON404 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteV1ApiKeysByIdResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1ApiKeysByIdResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1CreditsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Balance Current credit balance
		Balance   int       `json:"balance"`
		UpdatedAt time.Time `json:"updatedAt"`

		// UserId User ID
		UserId string `json:"userId"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV1CreditsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CreditsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1CreditsPurchaseResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Amount      int                `json:"amount"`
		CompletedAt time.Time          `json:"completedAt"`
		CreatedAt   time.Time          `json:"createdAt"`
		Id          openapi_types.UUID `json:"id"`
		NewBalance  int                `json:"newBalance"`
		Status      string             `json:"status"`
		UserId      string             `json:"userId"`
	}
	JSON400 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON402 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r PostV1CreditsPurchaseResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1CreditsPurchaseResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ScansResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV1ScansResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ScansResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1ScansResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// Deduplicated True if this request returned an existing scan (in-flight or cached completed) instead of creating a new one
		Deduplicated *bool `json:"deduplicated,omitempty"`

		// Id Scan job ID
		Id openapi_types.UUID `json:"id"`

		// State Current state of the scan job. COMPLETED when returned from cache (deduplicated); in-progress states when a new or in-flight job is returned.
		State PostV1Scans201State `json:"state"`
	}
}
type PostV1Scans201State string

// Status returns HTTPResponse.Status
func (r PostV1ScansResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1ScansResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1ScansBatchResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		// BatchId Batch ID for listing jobs by batch
		BatchId openapi_types.UUID `json:"batchId"`
		Jobs    []struct {
			// Deduplicated True if this URL returned an existing in-flight scan instead of creating a new one
			Deduplicated *bool `json:"deduplicated,omitempty"`

			// Id Scan job ID
			Id openapi_types.UUID `json:"id"`

			// State Current state (may be in-progress if deduplicated)
			State PostV1ScansBatch201JobsState `json:"state"`

			// Url Scanned URL
			Url string `json:"url"`
		} `json:"jobs"`
	}
}
type PostV1ScansBatch201JobsState string

// Status returns HTTPResponse.Status
func (r PostV1ScansBatchResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1ScansBatchResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ScansByIdResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		CompletedAt  *time.Time         `json:"completedAt,omitempty"`
		CreatedAt    time.Time          `json:"createdAt"`
		DurationMs   *int               `json:"durationMs,omitempty"`
		ErrorMessage *string            `json:"errorMessage,omitempty"`
		Id           openapi_types.UUID `json:"id"`
		Result       *struct {
			AnalysisMetadata *map[string]interface{} `json:"analysisMetadata,omitempty"`
			Categories       []string                `json:"categories"`
			ConfidenceScore  float32                 `json:"confidenceScore"`
			ContentHash      string                  `json:"contentHash"`
			ContentType      *string                 `json:"contentType"`
			HttpHeaders      map[string]string       `json:"httpHeaders"`
			HttpStatus       *int                    `json:"httpStatus"`
			Indicators       []string                `json:"indicators"`
			ModelUsed        string                  `json:"modelUsed"`
			Reasoning        string                  `json:"reasoning"`
			RiskScore        int                     `json:"riskScore"`
		} `json:"result"`
		StartedAt *time.Time             `json:"startedAt,omitempty"`
		State     GetV1ScansById200State `json:"state"`
		TimeoutAt *time.Time             `json:"timeoutAt,omitempty"`
		UpdatedAt time.Time              `json:"updatedAt"`
		Url       string                 `json:"url"`
		WorkerId  *string                `json:"workerId,omitempty"`
	}
	JSON404 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}
type GetV1ScansById200State string

// Status returns HTTPResponse.Status
func (r GetV1ScansByIdResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ScansByIdResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ScansByIdAnalyticsResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV1ScansByIdAnalyticsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ScansByIdAnalyticsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ScansByIdEventsResp struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetV1ScansByIdEventsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ScansByIdEventsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1SettingsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// ClerkUserId Clerk user ID (format: user_xxxxx)
		ClerkUserId          string                  `json:"clerkUserId"`
		CreatedAt            time.Time               `json:"createdAt"`
		Metadata             *map[string]interface{} `json:"metadata,omitempty"`
		SafeDomainPatterns   []string                `json:"safeDomainPatterns"`
		UnsafeDomainPatterns []string                `json:"unsafeDomainPatterns"`
		UpdatedAt            time.Time               `json:"updatedAt"`
	}
	JSON404 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r GetV1SettingsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1SettingsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutV1SettingsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// ClerkUserId Clerk user ID (format: user_xxxxx)
		ClerkUserId          string                  `json:"clerkUserId"`
		CreatedAt            time.Time               `json:"createdAt"`
		Metadata             *map[string]interface{} `json:"metadata,omitempty"`
		SafeDomainPatterns   []string                `json:"safeDomainPatterns"`
		UnsafeDomainPatterns []string                `json:"unsafeDomainPatterns"`
		UpdatedAt            time.Time               `json:"updatedAt"`
	}
	JSON404 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
	JSON500 *struct {
		Error struct {
			// Code Machine-readable error code
			Code string `json:"code"`

			// Details Additional error details
			Details *map[string]interface{} `json:"details,omitempty"`

			// Message Human-readable error message
			Message string `json:"message"`
		} `json:"error"`
		RequestId *openapi_types.UUID `json:"requestId,omitempty"`
		Timestamp time.Time           `json:"timestamp"`
	}
}

// Status returns HTTPResponse.Status
func (r PutV1SettingsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutV1SettingsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthWithResponse request returning *GetHealthResp
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResp, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResp(rsp)
}

// GetV1ApiKeysWithResponse request returning *GetV1ApiKeysResp
func (c *ClientWithResponses) GetV1ApiKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ApiKeysResp, error) {
	rsp, err := c.GetV1ApiKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ApiKeysResp(rsp)
}

// PostV1ApiKeysWithBodyWithResponse request with arbitrary body returning *PostV1ApiKeysResp
func (c *ClientWithResponses) PostV1ApiKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error) {
	rsp, err := c.PostV1ApiKeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ApiKeysResp(rsp)
}

func (c *ClientWithResponses) PostV1ApiKeysWithResponse(ctx context.Context, body PostV1ApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error) {
	rsp, err := c.PostV1ApiKeys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ApiKeysResp(rsp)
}

func (c *ClientWithResponses) PostV1ApiKeysWithFormdataBodyWithResponse(ctx context.Context, body PostV1ApiKeysFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ApiKeysResp, error) {
	rsp, err := c.PostV1ApiKeysWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ApiKeysResp(rsp)
}

// DeleteV1ApiKeysByIdWithResponse request returning *DeleteV1ApiKeysByIdResp
func (c *ClientWithResponses) DeleteV1ApiKeysByIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteV1ApiKeysByIdResp, error) {
	rsp, err := c.DeleteV1ApiKeysById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1ApiKeysByIdResp(rsp)
}

// GetV1CreditsWithResponse request returning *GetV1CreditsResp
func (c *ClientWithResponses) GetV1CreditsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1CreditsResp, error) {
	rsp, err := c.GetV1Credits(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CreditsResp(rsp)
}

// PostV1CreditsPurchaseWithBodyWithResponse request with arbitrary body returning *PostV1CreditsPurchaseResp
func (c *ClientWithResponses) PostV1CreditsPurchaseWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error) {
	rsp, err := c.PostV1CreditsPurchaseWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CreditsPurchaseResp(rsp)
}

func (c *ClientWithResponses) PostV1CreditsPurchaseWithResponse(ctx context.Context, body PostV1CreditsPurchaseJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error) {
	rsp, err := c.PostV1CreditsPurchase(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CreditsPurchaseResp(rsp)
}

func (c *ClientWithResponses) PostV1CreditsPurchaseWithFormdataBodyWithResponse(ctx context.Context, body PostV1CreditsPurchaseFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1CreditsPurchaseResp, error) {
	rsp, err := c.PostV1CreditsPurchaseWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1CreditsPurchaseResp(rsp)
}

// GetV1ScansWithResponse request returning *GetV1ScansResp
func (c *ClientWithResponses) GetV1ScansWithResponse(ctx context.Context, params *GetV1ScansParams, reqEditors ...RequestEditorFn) (*GetV1ScansResp, error) {
	rsp, err := c.GetV1Scans(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ScansResp(rsp)
}

// PostV1ScansWithBodyWithResponse request with arbitrary body returning *PostV1ScansResp
func (c *ClientWithResponses) PostV1ScansWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error) {
	rsp, err := c.PostV1ScansWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansResp(rsp)
}

func (c *ClientWithResponses) PostV1ScansWithResponse(ctx context.Context, body PostV1ScansJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error) {
	rsp, err := c.PostV1Scans(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansResp(rsp)
}

func (c *ClientWithResponses) PostV1ScansWithFormdataBodyWithResponse(ctx context.Context, body PostV1ScansFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansResp, error) {
	rsp, err := c.PostV1ScansWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansResp(rsp)
}

// PostV1ScansBatchWithBodyWithResponse request with arbitrary body returning *PostV1ScansBatchResp
func (c *ClientWithResponses) PostV1ScansBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error) {
	rsp, err := c.PostV1ScansBatchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansBatchResp(rsp)
}

func (c *ClientWithResponses) PostV1ScansBatchWithResponse(ctx context.Context, body PostV1ScansBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error) {
	rsp, err := c.PostV1ScansBatch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansBatchResp(rsp)
}

func (c *ClientWithResponses) PostV1ScansBatchWithFormdataBodyWithResponse(ctx context.Context, body PostV1ScansBatchFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostV1ScansBatchResp, error) {
	rsp, err := c.PostV1ScansBatchWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1ScansBatchResp(rsp)
}

// GetV1ScansByIdWithResponse request returning *GetV1ScansByIdResp
func (c *ClientWithResponses) GetV1ScansByIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdResp, error) {
	rsp, err := c.GetV1ScansById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ScansByIdResp(rsp)
}

// GetV1ScansByIdAnalyticsWithResponse request returning *GetV1ScansByIdAnalyticsResp
func (c *ClientWithResponses) GetV1ScansByIdAnalyticsWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdAnalyticsResp, error) {
	rsp, err := c.GetV1ScansByIdAnalytics(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ScansByIdAnalyticsResp(rsp)
}

// GetV1ScansByIdEventsWithResponse request returning *GetV1ScansByIdEventsResp
func (c *ClientWithResponses) GetV1ScansByIdEventsWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetV1ScansByIdEventsResp, error) {
	rsp, err := c.GetV1ScansByIdEvents(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ScansByIdEventsResp(rsp)
}

// GetV1SettingsWithResponse request returning *GetV1SettingsResp
func (c *ClientWithResponses) GetV1SettingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1SettingsResp, error) {
	rsp, err := c.GetV1Settings(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1SettingsResp(rsp)
}

// PutV1SettingsWithBodyWithResponse request with arbitrary body returning *PutV1SettingsResp
func (c *ClientWithResponses) PutV1SettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error) {
	rsp, err := c.PutV1SettingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutV1SettingsResp(rsp)
}

func (c *ClientWithResponses) PutV1SettingsWithResponse(ctx context.Context, body PutV1SettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error) {
	rsp, err := c.PutV1Settings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutV1SettingsResp(rsp)
}

func (c *ClientWithResponses) PutV1SettingsWithFormdataBodyWithResponse(ctx context.Context, body PutV1SettingsFormdataRequestBody, reqEditors ...RequestEditorFn) (*PutV1SettingsResp, error) {
	rsp, err := c.PutV1SettingsWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutV1SettingsResp(rsp)
}

// ParseGetHealthResp parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResp(rsp *http.Response) (*GetHealthResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1ApiKeysResp parses an HTTP response from a GetV1ApiKeysWithResponse call
func ParseGetV1ApiKeysResp(rsp *http.Response) (*GetV1ApiKeysResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ApiKeysResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			CreatedAt  time.Time          `json:"createdAt"`
			ExpiresAt  *time.Time         `json:"expiresAt"`
			Id         openapi_types.UUID `json:"id"`
			LastUsedAt *time.Time         `json:"lastUsedAt"`
			Name       string             `json:"name"`
			RevokedAt  *time.Time         `json:"revokedAt"`
			Scopes     []string           `json:"scopes"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1ApiKeysResp parses an HTTP response from a PostV1ApiKeysWithResponse call
func ParsePostV1ApiKeysResp(rsp *http.Response) (*PostV1ApiKeysResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1ApiKeysResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			CreatedAt time.Time          `json:"createdAt"`
			Id        openapi_types.UUID `json:"id"`

			// Key Plaintext API key (only shown once)
			Key  string `json:"key"`
			Name string `json:"name"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteV1ApiKeysByIdResp parses an HTTP response from a DeleteV1ApiKeysByIdWithResponse call
func ParseDeleteV1ApiKeysByIdResp(rsp *http.Response) (*DeleteV1ApiKeysByIdResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1ApiKeysByIdResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Id ID of the revoked API key
			Id openapi_types.UUID `json:"id"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1CreditsResp parses an HTTP response from a GetV1CreditsWithResponse call
func ParseGetV1CreditsResp(rsp *http.Response) (*GetV1CreditsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CreditsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Balance Current credit balance
			Balance   int       `json:"balance"`
			UpdatedAt time.Time `json:"updatedAt"`

			// UserId User ID
			UserId string `json:"userId"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostV1CreditsPurchaseResp parses an HTTP response from a PostV1CreditsPurchaseWithResponse call
func ParsePostV1CreditsPurchaseResp(rsp *http.Response) (*PostV1CreditsPurchaseResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1CreditsPurchaseResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Amount      int                `json:"amount"`
			CompletedAt time.Time          `json:"completedAt"`
			CreatedAt   time.Time          `json:"createdAt"`
			Id          openapi_types.UUID `json:"id"`
			NewBalance  int                `json:"newBalance"`
			Status      string             `json:"status"`
			UserId      string             `json:"userId"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 402:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON402 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1ScansResp parses an HTTP response from a GetV1ScansWithResponse call
func ParseGetV1ScansResp(rsp *http.Response) (*GetV1ScansResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ScansResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostV1ScansResp parses an HTTP response from a PostV1ScansWithResponse call
func ParsePostV1ScansResp(rsp *http.Response) (*PostV1ScansResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1ScansResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// Deduplicated True if this request returned an existing scan (in-flight or cached completed) instead of creating a new one
			Deduplicated *bool `json:"deduplicated,omitempty"`

			// Id Scan job ID
			Id openapi_types.UUID `json:"id"`

			// State Current state of the scan job. COMPLETED when returned from cache (deduplicated); in-progress states when a new or in-flight job is returned.
			State PostV1Scans201State `json:"state"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParsePostV1ScansBatchResp parses an HTTP response from a PostV1ScansBatchWithResponse call
func ParsePostV1ScansBatchResp(rsp *http.Response) (*PostV1ScansBatchResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1ScansBatchResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// BatchId Batch ID for listing jobs by batch
			BatchId openapi_types.UUID `json:"batchId"`
			Jobs    []struct {
				// Deduplicated True if this URL returned an existing in-flight scan instead of creating a new one
				Deduplicated *bool `json:"deduplicated,omitempty"`

				// Id Scan job ID
				Id openapi_types.UUID `json:"id"`

				// State Current state (may be in-progress if deduplicated)
				State PostV1ScansBatch201JobsState `json:"state"`

				// Url Scanned URL
				Url string `json:"url"`
			} `json:"jobs"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetV1ScansByIdResp parses an HTTP response from a GetV1ScansByIdWithResponse call
func ParseGetV1ScansByIdResp(rsp *http.Response) (*GetV1ScansByIdResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ScansByIdResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CompletedAt  *time.Time         `json:"completedAt,omitempty"`
			CreatedAt    time.Time          `json:"createdAt"`
			DurationMs   *int               `json:"durationMs,omitempty"`
			ErrorMessage *string            `json:"errorMessage,omitempty"`
			Id           openapi_types.UUID `json:"id"`
			Result       *struct {
				AnalysisMetadata *map[string]interface{} `json:"analysisMetadata,omitempty"`
				Categories       []string                `json:"categories"`
				ConfidenceScore  float32                 `json:"confidenceScore"`
				ContentHash      string                  `json:"contentHash"`
				ContentType      *string                 `json:"contentType"`
				HttpHeaders      map[string]string       `json:"httpHeaders"`
				HttpStatus       *int                    `json:"httpStatus"`
				Indicators       []string                `json:"indicators"`
				ModelUsed        string                  `json:"modelUsed"`
				Reasoning        string                  `json:"reasoning"`
				RiskScore        int                     `json:"riskScore"`
			} `json:"result"`
			StartedAt *time.Time             `json:"startedAt,omitempty"`
			State     GetV1ScansById200State `json:"state"`
			TimeoutAt *time.Time             `json:"timeoutAt,omitempty"`
			UpdatedAt time.Time              `json:"updatedAt"`
			Url       string                 `json:"url"`
			WorkerId  *string                `json:"workerId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetV1ScansByIdAnalyticsResp parses an HTTP response from a GetV1ScansByIdAnalyticsWithResponse call
func ParseGetV1ScansByIdAnalyticsResp(rsp *http.Response) (*GetV1ScansByIdAnalyticsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ScansByIdAnalyticsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1ScansByIdEventsResp parses an HTTP response from a GetV1ScansByIdEventsWithResponse call
func ParseGetV1ScansByIdEventsResp(rsp *http.Response) (*GetV1ScansByIdEventsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ScansByIdEventsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetV1SettingsResp parses an HTTP response from a GetV1SettingsWithResponse call
func ParseGetV1SettingsResp(rsp *http.Response) (*GetV1SettingsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1SettingsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// ClerkUserId Clerk user ID (format: user_xxxxx)
			ClerkUserId          string                  `json:"clerkUserId"`
			CreatedAt            time.Time               `json:"createdAt"`
			Metadata             *map[string]interface{} `json:"metadata,omitempty"`
			SafeDomainPatterns   []string                `json:"safeDomainPatterns"`
			UnsafeDomainPatterns []string                `json:"unsafeDomainPatterns"`
			UpdatedAt            time.Time               `json:"updatedAt"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutV1SettingsResp parses an HTTP response from a PutV1SettingsWithResponse call
func ParsePutV1SettingsResp(rsp *http.Response) (*PutV1SettingsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutV1SettingsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// ClerkUserId Clerk user ID (format: user_xxxxx)
			ClerkUserId          string                  `json:"clerkUserId"`
			CreatedAt            time.Time               `json:"createdAt"`
			Metadata             *map[string]interface{} `json:"metadata,omitempty"`
			SafeDomainPatterns   []string                `json:"safeDomainPatterns"`
			UnsafeDomainPatterns []string                `json:"unsafeDomainPatterns"`
			UpdatedAt            time.Time               `json:"updatedAt"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error struct {
				// Code Machine-readable error code
				Code string `json:"code"`

				// Details Additional error details
				Details *map[string]interface{} `json:"details,omitempty"`

				// Message Human-readable error message
				Message string `json:"message"`
			} `json:"error"`
			RequestId *openapi_types.UUID `json:"requestId,omitempty"`
			Timestamp time.Time           `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
